---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: reading.md
  label: "\U0001F4DA Reading"
  match: "**/*"
- type: document
  path: writing.md
  label: Writing
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _data
  label: Data
  create: all
  match: "*.yml"
  new_doc_ext: yml
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
